### ISSUE TITLE
send message failed

### ISSUE THREAD

**Issue by li-xunhuan** [lddsb/drone-dingtalk-message#14]
![1](https://user-images.githubusercontent.com/10476982/71764498-7b775380-2f23-11ea-946e-c7291e95a9ed.png)
![2](https://user-images.githubusercontent.com/10476982/71764499-7c0fea00-2f23-11ea-8652-5043fb88afbb.png)

**Comment by lddsb** [comment]
你在创建机器人的时候设置了关键词限制，消息主题里面必须包含所设置的关键词

**Comment by li-xunhuan** [comment]
> 你在创建机器人的时候设置了关键词限制，消息主题里面必须包含所设置的关键词

果不其然，感谢感谢！！！
您不说我都忘了我设了关键字的！！！

**Comment by li-xunhuan** [comment]
那么问题来了，我应该在钉钉加啥关键字啊？
我加了build，还是失败了！

**Comment by lddsb** [comment]
> 那么问题来了，我应该在钉钉加啥关键字啊？
> 我加了build，还是失败了！

你有使用自定义模版吗？如果没有那么使用自定义模版然后在模版中加入你设置的关键词就可以了。

**Comment by li-xunhuan** [comment]
> 你有使用自定义模版吗？如果没有那么使用自定义模版然后在模版中加入你设置的关键词就可以了。

没有用，就用的默认的！

**Comment by lddsb** [comment]
> > 你有使用自定义模版吗？如果没有那么使用自定义模版然后在模版中加入你设置的关键词就可以了。
> 
> 没有用，就用的默认的！

那你还是自定义一下模版吧，用自定义模版，然后在模版里面加入设置好的关键词就可以了。

**Comment by li-xunhuan** [comment]
> 那你还是自定义一下模版吧，用自定义模版，然后在模版里面加入设置好的关键词就可以了。

好的，感谢回复！！
