### ISSUE TITLE
The message's picture url is not found from sina server

### ISSUE THREAD

**Issue by curder** [lddsb/drone-dingtalk-message#15]
Hi, The message's picture url is not found from sina server:

- **success picture url**
`https://ws4.sinaimg.cn/large/006tNc79gy1fz05g5a7utj30he0bfjry.jpg`

- **failure picture url**
`https://ws1.sinaimg.cn/large/006tNc79gy1fz0b4fghpnj30hd0bdmxn.jpg`

thanks!

**Comment by lddsb** [comment]
thx for your report, I'll fix it soon ..

**Comment by lddsb** [comment]
It's ok now, please update to the latest version.
