### ISSUE TITLE
can't send message

### ISSUE THREAD

**Issue by imdingtalk** [lddsb/drone-dingtalk-message#2]
my version:
drone/drone:1.2.3-linux-amd64
drone/agent:1.2.3-linux-amd64 

![image](https://user-images.githubusercontent.com/16778873/62629112-2678e680-b95f-11e9-814b-308fb446ff62.png)
![image](https://user-images.githubusercontent.com/16778873/62629133-2ed12180-b95f-11e9-9c3f-330b4b7f19bb.png)

**Comment by vaddenz** [comment]
You wanna use the access_token only, remove 'https://oapi.......?access_tooken='.  Just figured it out too :D

**Comment by lddsb** [comment]
You need to fill in the token instead of the full URL

**Comment by lddsb** [comment]
You can update `lddsb/drone-dingtalk-message` to `1.1.1` or newer version to solve this problem.
