### ISSUE TITLE
关于自定义变量

### ISSUE THREAD

**Issue by pc10201** [lddsb/drone-dingtalk-message#21]
能否获取发布ID？
或者自己定义变量然后传入模板？

**Comment by lddsb** [comment]
自定义变量是有想过的，不过因为最近比较忙，所以一直没有去做，如果你有什么想法的话，欢迎你的PR

**Comment by larants** [comment]
我也有同样的疑问，如何获取发布ID？没看到这个环境变量

**Comment by lddsb** [comment]
#28 
将会支持在模板文件中 `[DRONE_COMMIT_AUTHOR]` 这样的方式直接读取`Drone CI`内置的变量

**Comment by lddsb** [comment]
请使用 `1.2.5`版本插件实现自定义变量

```shell
docker pull lddsb/drone-dingtalk-message:1.2.5
```
