### ISSUE TITLE
TPL_BUILD_CONSUMING数值都是0

### ISSUE THREAD

**Issue by pc10201** [lddsb/drone-dingtalk-message#22]
看文档中说明
TPL_BUILD_CONSUMING是整个构建的时间
但我这边测试下来，无论构建时间是多久
TPL_BUILD_CONSUMING都是0秒

用的是当前最新的lddsb/drone-dingtalk-message镜像

**Comment by larants** [comment]
确实是这样

**Comment by lddsb** [comment]
麻烦提供一下 drone 的版本

**Comment by lddsb** [comment]
经测试发现应该是 [k8s的部分不兼容导致的](https://docs.drone.io/runner/kubernetes/overview/)
![image](https://user-images.githubusercontent.com/20765867/80557656-3616ee80-8a0a-11ea-963c-5a0251562417.png)

目前主要版本已经发布补丁，请使用最新版本以解决这个问题。最新版本包含以下版本：
- 1.2.4
- 1.2
- 1.1.4
- 1.1
- latest

**Comment by pc10201** [comment]
我没有用k8s啊，只用了drone,docker和drone ansible插件

**Comment by pc10201** [comment]
> 麻烦提供一下 drone 的版本

1.6.5和1.7.0都有这个问题

**Comment by lddsb** [comment]
请使用 `1.2.6` 以后的版本以解决这个问题
