### ISSUE TITLE
atMobile没有实现传入吗

### ISSUE THREAD

**Issue by LGinC** [lddsb/drone-dingtalk-message#26]
![image](https://user-images.githubusercontent.com/15363011/95644830-ea558e80-0aeb-11eb-968a-9cb00e973a39.png)

**Comment by lddsb** [comment]
这个暂时没有实现，需要at某个人的时候感觉操作比较繁琐，如果有什么好的想法欢迎pr

**Comment by LGinC** [comment]
奇怪，你这里明明都在content里追加了@手机号了，实际效果确是没有@到
[https://github.com/lddsb/dingtalk-webhook/blob/c98992940848434092a7f896147753aafdbe5785/webhook.go#L189](https://github.com/lddsb/dingtalk-webhook/blob/c98992940848434092a7f896147753aafdbe5785/webhook.go#L189)

按理说只要在.drone.yml里配置msg_at_mobiles 应该就可以才对呀

**Comment by lddsb** [comment]
> 奇怪，你这里明明都在content里追加了@手机号了，实际效果确是没有@到
> https://github.com/lddsb/dingtalk-webhook/blob/c98992940848434092a7f896147753aafdbe5785/webhook.go#L189
> 
> 按理说只要在.drone.yml里配置msg_at_mobiles 应该就可以才对呀

我今天抽时间改一下吧，这个功能是刚需吗？

**Comment by LGinC** [comment]
> > 奇怪，你这里明明都在content里追加了@手机号了，实际效果确是没有@到
> > https://github.com/lddsb/dingtalk-webhook/blob/c98992940848434092a7f896147753aafdbe5785/webhook.go#L189
> > 按理说只要在.drone.yml里配置msg_at_mobiles 应该就可以才对呀
> 
> 我今天抽时间改一下吧，这个功能是刚需吗？

是的, 不同项目需要通知不同的人


好像是手机号正则的问题,对新号段的匹配不到
`(13\d|14[579]|15[^4\D]|17[^49\D]|18\d)\d{8}`  可以试试这个,这个范围更广一点

**Comment by LGinC** [comment]
提交PR了

**Comment by lddsb** [comment]
#34 已修复艾特不到人的BUG
请更新到 `1.2.7`

[可以查看一下README参考用法](https://github.com/lddsb/drone-dingtalk-message/blob/master/README_ZH.md#%E6%A8%A1%E7%89%88)
