### ISSUE TITLE
请问promote的target属性怎么配置

### ISSUE THREAD

**Issue by coolgin** [lddsb/drone-dingtalk-message#32]
when:
      event:
        - promote
      target:
        - test
    想在发版完成后通知发布的是哪个环境

**Comment by coolgin** [comment]
这个变量DRONE_DEPLOY_TO

**Comment by lddsb** [comment]
这个应该是你哪些环境需要就写上吧，这个是 `Drone` 的语法，按理是适用于所有插件的

**Comment by coolgin** [comment]
![image](https://user-images.githubusercontent.com/61035632/113980979-b4664c80-9879-11eb-954f-70436b95e600.png)
开发测试环境现在共用一个分支，发版的时候通知下是发的哪个环境，上面那个变量可以，我已经加上了

**Comment by lddsb** [comment]
好的，很高兴你解决了问题，如果可以麻烦关一下 `issue`
