### ISSUE TITLE
User can customize the notification title.

### ISSUE THREAD

**Issue by curder** [lddsb/drone-dingtalk-message#5]
DingTalk title Is "new message"，I want modify it in different project.

I found it in [plugin.go#L152](https://github.com/lddsb/drone-dingtalk-message/blob/master/plugin.go#L152), but I don't know how to change it.

- Mac DingTalk Client

![image](https://user-images.githubusercontent.com/8327004/66694430-cd725980-ece5-11e9-890d-e733b7419ea3.png)

- Apple Watch Client

![1871570851969_ pic](https://user-images.githubusercontent.com/8327004/66694438-e67b0a80-ece5-11e9-9792-e2fa496b009f.jpg)

Please give me some help, thanks.

**Comment by lddsb** [comment]
it's a bug, i will add the option soon.

**Comment by lddsb** [comment]
#6 it's fix now, you can upgrade your image to fix it.
