### ISSUE TITLE
如何插入图片

### ISSUE THREAD

**Issue by monstereat** [lddsb/drone-dingtalk-message#52]
image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingtalk_smartfarmcd_token
      type: markdown
      failure_color: FF0000
      sha_link: true
      message_pic: true
      failure_pic: 图片url
      success_pic: 图片url
      debug: true
      tpl: |
        ### [TPL_REPO_SHORT_NAME]的[TPL_COMMIT_BRANCH] 发布 [TPL_BUILD_STATUS] (`耗时 [TPL_BUILD_CONSUMING]s`)

        发布状态：![图片([TPL_STATUS_PIC])
        
        更新内容: [TPL_COMMIT_MSG]
        
        更新详情: [[TPL_COMMIT_SHA]]([TPL_COMMIT_LINK])
        
        更新作者: [[TPL_AUTHOR_NAME]([TPL_AUTHOR_EMAIL])](mailto:[TPL_AUTHOR_EMAIL])
        
        [点击查看打包详情 [TPL_STATUS_EMOTICON]]([TPL_BUILD_LINK])

![image](https://user-images.githubusercontent.com/13077554/222020647-049c420d-b352-43a8-a11e-4130c66fc687.png)

这样插入图片失败，能不能给个demo

类似于这个模版可以给个demo么

![image](https://user-images.githubusercontent.com/13077554/222024189-21256f83-51b0-4ae4-8084-dd4875a224ad.png)

**Comment by hanzhiyan588** [comment]
![success]([TPL_STATUS_PIC])

**Comment by hanzhiyan588** [comment]
![image](https://user-images.githubusercontent.com/63633319/224950943-9c4d27d7-968a-40bf-b32c-248ad24f3bd3.png)
无需定义任何参数

**Comment by monstereat** [comment]
> ![image](https://user-images.githubusercontent.com/63633319/224950943-9c4d27d7-968a-40bf-b32c-248ad24f3bd3.png) 无需定义任何参数

好滴 好滴  谢谢     问题已解决
