### ISSUE TITLE
hi,how to get the access token?

### ISSUE THREAD

**Issue by newtonsu** [lddsb/drone-dingtalk-message#8]
hi
  I want to use drone-dingtalk .Can you tell me more about how to get the access token.

token
you can get the access token when you add a bot in a group

**Comment by lddsb** [comment]
First of all, you need to create or join a dingtalk group, and then, you can follow the picture tutorial below:

![image](https://user-images.githubusercontent.com/20765867/69546874-83acac80-0fcf-11ea-87e5-1cee9ee16751.png)

![image](https://user-images.githubusercontent.com/20765867/69547031-ce2e2900-0fcf-11ea-9cc9-0cb20626c72f.png)

![image](https://user-images.githubusercontent.com/20765867/69547075-e7cf7080-0fcf-11ea-8b73-b37b5b9b8939.png)

![image](https://user-images.githubusercontent.com/20765867/69547203-1a796900-0fd0-11ea-88bf-1f8cb3be1a0b.png)

![image](https://user-images.githubusercontent.com/20765867/69547523-b6a37000-0fd0-11ea-87ab-57f2d32e8bb3.png)

![image](https://user-images.githubusercontent.com/20765867/69547637-efdbe000-0fd0-11ea-84f9-2a95838b6ec2.png)

**Comment by lddsb** [comment]
I believe you can solve this issue now.

**Comment by newtonsu** [comment]
Thank you very much, this worked for me
